stages:
  - test

test:
    image: cypress/browsers:node16.16.0-chrome107-ff107
    stage: test
    script:
    - npm ci
    - npm run runOnChrome

    artifacts:
      when: always
      paths:
        - cypress/videos/**/.mp4
        - cypress/screenshots/**/.png